version: '3.7'

services:
  jupyterhub:
    build: jupyterhub
    image: jupyterhub_img
    container_name: jupyterhub
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - jupyterhub_data:/srv/jupyterhub
    networks:
      - hale-bopp-network
    environment:
      - DOCKER_JUPYTER_CONTAINER=jupyterlab_img
      - DOCKER_NETWORK_NAME=${COMPOSE_PROJECT_NAME}_default
      - HUB_IP=jupyterhub
      - HOST
      - OAUTH_CALLBACK_URL=http://jupyter.docker.localhost/hub/oauth_callback //add
      - OAUTH_CLIENT_ID=jupyterhub     //add
      - OAUTH_CLIENT_SECRET=181504b4-fc17-486f-8023-be5759d4e3d6 //add
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.jupyterhub.rule=Host(`jupyterhub.docker.localhost`)"
    restart: on-failure

  jupyterlab:
    build: jupyterlab
    image: jupyterlab_img
    container_name: jupyterlab
    network_mode: none
    command: echo
    deploy:
      resources:
        limits: 
          memory: 50M
        reservations:
          memory: 20M

  reverse-proxy:
    image: traefik:v2.4
    container_name: reverse_proxy
    networks:
      - hale-bopp-network
    command: --api.insecure=true --providers.docker
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: on-failure

  oauth2:
    build: oauth2
    image: oauth2_img
    container_name: oauth2
    ports:
      - "8888:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - keycloak_data:/srv/jupyterhub
    environment:
      # DB_VENDOR: POSTGRES
      # DB_ADDR: postgres
      #DB_DATABASE: keycloak
      #DB_USER: keycloak
      #DB_SCHEMA: public
      #DB_PASSWORD: password
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
      - HOST
      - KEYCLOAK_FRONTEND_URL=http://localhost:8888/auth
      #- #JDBC_PARAMS: "ssl=true"
    labels:
      - "traefik.http.routers.oauth2.rule=Host(`oauth2.docker.localhost`)"
    restart: on-failure

  database:
    image: postgres:10.17-alpine
    container_name: db
    environment:
      - USER=super
      - POSTGRES_USER=keycloak
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=keycloak
      - HOST
    volumes:
      - type: volume
        source: database_data
        target: /var/lib/postgresql/data
    networks:
      - hale-bopp-network


volumes:
  jupyterhub_data:
    driver: local
  keycloak_data:
    driver: local
  database_data:
    driver: local

networks:
  hale-bopp-network:
    external: true